language: go
services:
  - docker
go:
  - 1.10.x
before_install:
  - go get -t ./...
install:
  - go get github.com/mitchellh/gox
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - bash ./travisbuild.sh
deploy:
  - provider: releases
    file_glob: true
    skip_cleanup: true
    api_key: "${GITHUB_TOKEN}"
    file: "./build/*"
    on:
      tags: true
  - provider: script
    script: docker push tinyzimmer/cloudtail
    on:
      tags: true
