language: go
go:
  - 1.10.x
before_install:
  - go get -t ./...
install:
  - go get github.com/mitchellh/gox
script:
  - ./travisbuild.sh
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: "${GITHUB_TOKEN}"
  file: "./build/*"
  on:
    tags: true
