language: go
go:
- 1.10.x
before_install:
- go get -t ./...
install:
- go get github.com/mitchellh/gox
script:
- gox -os="linux darwin windows" -arch="amd64 386" -output="./build/{{.Dir}}_{{.OS}}_{{.Arch}}"
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: VFM+lz0g/xV4df92jD6XJp5NeR2DD4zTXAsYChAMNfMZZC4CswQTf6SsURtuF4fJpGl1Hn+XIWQEv1/CVSIyb2fs1iMp2CmEk1EbC79ooXAxctUXs2JXnaeE6OdbgfBHnkbshR9gYI6GZCFCDUfSBS3S7oXPfyWu+LhpH9KPVvGFqCGTxOta6tnxkX1IOvwuhn+cYVS9uRl0i9cx/89rXlPrHUsMD6VDV3ZEYJHSAvBAfKUjKOya0wPsusj4vup1fT6brFDyGPGwRCn3kVsKH/Fa/1HxTK2vozzfEhVyQSzRx20Tr2DUj+nJ4Vk0NMdcZitoYNkUESavPSNpdE1Cqs2wh9JoEZoKcFQJSOf7sr2xemmqqTOYJ6907mFEJUJlgtpp8iawKcnPRDJifgWH1tqORPgxjFXqN/rCyfxwBsOSJtZ57PgtoBytgt+7Ax2BGz+aR0qCgrTnB+77visa3/97IA4ZHU18LRL2sE/ZY5I9VbCGv686tec/Xdz4g0LiKIFlcoWT+q0XnDsW4R4/2wtSZsmDG1lpYA/djPjzl0ijo09vaDs73vwlrAtsehfCTTbXJ2eq2gyndSC6tF9YT0tfHXufzBpc8oWoUefkA+bB+iHsXwrU72w5aD6hET2oyIMZnojNcU3POhYBeOrNLrpTVEZ3S1kD+5Ouv98UWR8=
  file: "./build/*"
  on:
    repo: tinyzimmer/cloudtail
